//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hisoft {
    
    
    public partial class List_News {
        
        /// <summary>
        /// TinNoiBat1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebsiteV2.UserControl.TinTuc.TinNoiBat TinNoiBat1;
        
        /// <summary>
        /// TinMoiNhat1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebsiteV2.UserControl.TinTuc.TinMoiNhat TinMoiNhat1;
        
        /// <summary>
        /// TinDoc1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebsiteV2.UserControl.TinTuc.TinDoc TinDoc1;
    }
}
